trigger:
- main

resources:
- repo: self

variables:
  imageRepo: simpleapp
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'mytestacr0901'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/app'
        artifact: 'drop'
        publishLocation: 'pipeline'          

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build  
  variables:
     acrsecret: k8examplesacrauth 
  jobs:
    - job: Deploy
      displayName: Deploy to AKS 
      pool:
        vmImage: ubuntu-latest\
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop'
          targetPath: '$(Pipeline.Workspace)/s/drop'
      - task: KubernetesManifest@0
        inputs:
          action: 'createSecret'
          kubernetesServiceConnection: 'Cluster_connection'
          namespace: 'default'
          secretType: 'dockerRegistry'
          secretName: '$(acrsecret)'
          dockerRegistryEndpoint: 'myacrtest0901'
   
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'Cluster_connection'
          namespace: 'default'
          manifests: $(Pipeline.Workspace)/s/drop/deployment.yml
          
    


