---
apiVersion: v1
kind: Pod
metadata:
  name: MyPod
  labels:
    app: simplaeapp
spec:
  containers:
  - name: simplaeapp-container
    image: myacrtest0901.azurecr.io/simpleapp
    ports:
      - containerPort: 8080


