---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-1
  labels:
    app: simplaeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simplaeapp-container
        image: ngnix:latest
        ports:
        - containerPort: 8080

