apiVersion: v1
kind: Deployment
metadata: 
   name: simpleapp
specs:
  replicaset: 3
  selector:
    matchlabels:
      app: simpleapp
  ports: 
    - port: 80
  template:
      metadata:
      labels:
        app: simpleapp
      specs:
        container: 
            - name: simplaeapp
              image: myacrtest0901.azurecr.io/simpleapp
              ports:
                - containerPort: 8080
--- 
apiVersion: apps/v1
kind: Service
metadata:
   labels:
     app: simpleapp
specs:
  type: loadbalancer
  ports:
    - name: https
      port: 80
      protocol: tcp
      targetPort: 8080
      selector:
        matchlabels: 
            app: simplaeapp 



         