---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-5
  labels:
    app: simpleapps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapps
  template:
    metadata:
      labels:
        app: simpleapps
    spec:
      containers:
      - name: simplaeapp-container
        image: myacrtest0901.azurecr.io/pythonapptest:latest
        ports:
        - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: k8-service
  labels:
    app: simpleapps
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: simpleapps

