---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-1
  labels:
    app: simplaeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simplaeapp-container
        image: nginx:latest
        ports:
        - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: k8-service
  labels:
    app: simpleapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: simpleapp

