---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: simplaeapp
spec:
  containers:
  - name: simplaeapp-container
    image: myacrtest0901.azurecr.io/bhubaneshdockerhelloworldflask:latest
    ports:
      - containerPort: 8080


